### ISSUE TITLE
tldRegexString.split is throwing due to it's a function, seem the expected value is an string.

### ISSUE THREAD

**Issue by gsi-alejandro** [ninoseki/fanger#50]
I'm using fanger library but this error is throwing while loading.

![image](https://user-images.githubusercontent.com/15661442/104341835-3ab40200-54c8-11eb-978a-05430a251176.png)

This example is a little bit more clear. (sorry about the compiled code, but in development mode is working ok)

![image](https://user-images.githubusercontent.com/15661442/104342557-f2e1aa80-54c8-11eb-98d2-32972775463b.png)

**Comment by gsi-alejandro** [comment]
Hi @ninoseki 
I find out what is happening and I already create a PR solving this issue -> https://github.com/ninoseki/fanger/pull/51

The problem was an update in the ioc-extrator dependency version 2.7, it has a breaking change, maybe should be published as v3 to avoid this problem.

Please approve and merge the PR or create your own PR fixing it, I want to use this package but it's broken right now.

**Comment by gsi-alejandro** [comment]
PD. The CI is failing because I don't update the package-lock.json, then it's installing the ioc-extractor version 2.6 where getTLDRegExpString does not exist yet until version 2.7

**Comment by ninoseki** [comment]
@gsi-alejandro Sorry, I was not careful.  
I just released a new version as a hotfix. (Change to use ioc-extractor v2.7.0)
It is because I made a mistake in the latest version of ioc-extractor. I will merge your PR after fix the issues in it.
